[versions]

compileSdk = "34"
targetSdk = "34"
versionCode = "1"
versionName = "1.0.0"
minSdk = "21"
jvmTarget = "17"

android = "8.4.0"
kotlin = "2.0.0-Beta5"

composeBom = "2024.05.00"
composeCompiler = "1.5.11-dev-k2.0.0-Beta5-b5a216d0ac6"

[plugins]

android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]

appcompat = "androidx.appcompat:appcompat:1.6.1"
refresh = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

flexbox = "com.google.android.flexbox:flexbox:3.0.0"
material = "com.google.android.material:material:1.12.0"
annotation = "androidx.annotation:annotation:1.7.1"
core = "androidx.core:core-ktx:1.13.1"
lifecycle = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0"

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-navigation = "androidx.navigation:navigation-compose:2.7.7"
compose-navigation-gson = "com.google.code.gson:gson:2.10.1"

[bundles]

flexbox = ["flexbox"]
extension = ["annotation", "core", "lifecycle"]
http = []

compose = [
    "compose-material",
    "compose-ui",
    "compose-navigation",
    "compose-navigation-gson",
    "compose-ui-tooling",
    "compose-ui-tooling-preview"
]

component-ui = [
    "appcompat",
    "material",
    "refresh",
]