[versions]

compileSdk = "34"
targetSdk = "34"
versionCode = "1"
versionName = "1.0.0"
minSdk = "23"
jvmTarget = "17"

android = "8.2.2"
kotlin = "1.9.22"

composeBom = "2024.01.00"
composeCompiler = "1.5.8"

[plugins]

android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]

appcompat = "androidx.appcompat:appcompat:1.6.1"
core = "androidx.core:core-ktx:1.12.0"
recyclerview = "androidx.recyclerview:recyclerview:1.3.2"
livedata = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0"
viewpager = "androidx.viewpager2:viewpager2:1.0.0"
material = "com.google.android.material:material:1.11.0"
refresh = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
gson = "com.google.code.gson:gson:2.10.1"
flexbox = "com.google.android.flexbox:flexbox:3.0.0"

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-activity = "androidx.activity:activity-compose:1.8.2"
compose-navigation = "androidx.navigation:navigation-compose:2.7.6"

[bundles]

androidx = [
    "appcompat",
    "core",
    "recyclerview",
    "livedata",
    "viewpager",
    "material",
    "refresh",
    "flexbox"
]

compose = [
    "compose-material3",
    "compose-material",
    "compose-activity",
    "compose-ui",
    "compose-navigation"
]
