[versions]

compildSdk = "34"
targetSdk = "34"
versionCode = "1"
versionName = "1.0.0"
minSdk = "23"
jvmTarget = "17"

android = "8.1.4"
kotlin = "1.9.20"

[plugins]

android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]

annotation = "androidx.annotation:annotation:1.7.0"
appcompat = "androidx.appcompat:appcompat:1.6.1"
core = "androidx.core:core-ktx:1.12.0"
recyclerview = "androidx.recyclerview:recyclerview:1.3.2"
livedata = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2"
viewpager = "androidx.viewpager2:viewpager2:1.0.0"

[bundles]

androidx = ["annotation", "appcompat", "core", "recyclerview", "livedata", "viewpager"]
